#!/usr/bin/env python3
"""Emit manifest.conf for this package from the tree itself.

The manifest is the index every consumer's kauk lays .claude links from.
It is never hand-edited: this generator IS the source of its content, so the
index cannot silently drift from the tree (the recorded failure mode: files
committed and tested here, distributed to nobody for missing manifest lines).

Regenerate with:  python3 tools/manifest_gen.py > manifest.conf
The delivery integration test fails when the committed manifest differs from
a regeneration.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# The manifest grammar takes one role token; skills carry hierarchical roles
# in frontmatter. The first listed role's family decides.
ROLE_FAMILY = {
    "general": "all",
    "process": "org",
    "development": "dev",
    "infrastructure": "infra",
}

HEADER = """\
# orchids manifest v2 — what this package exposes, one typed line per entry.
# GENERATED by tools/manifest_gen.py from the tree — regenerate, never hand-edit.
# Parsed by kauk (the kauk package); the engine hardcodes no layout — this
# file IS the grouping. Line types:
#   skill <name> <role>     src=skills/<name>/ → .claude/skills/<name>; role ∈
#                           dev|infra|org|all; delivery tuned per-repo in .ai.toml
#                           ([role] sections: exclude|copy|link|local, ["*"] default)
#   link <src> <dst>        absolute symlink into the clone; everyone gets it
#   template <src> <dst>    install-time copy (<project-name> substituted), then
#                           project-owned — never overwritten
#   prefix <src> <dst>      block idempotently kept at the head of dst
"""

def tracked_files(subdir: str) -> list[str]:
    """Repo-relative tracked paths directly under subdir — only committed
    content is distributed; runtime droppings never enter the index."""
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "--", subdir],
        capture_output=True, text=True, check=True,
    ).stdout
    return sorted(p for p in out.splitlines() if p.count("/") == 1)


def skill_role(skill_dir: Path) -> str:
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    inline = re.search(r"^roles:\s*\[([^\]]*)\]", text, re.M)
    if inline:
        first = inline.group(1).split(",")[0].strip()
    else:
        block = re.search(r"^roles:\s*\n((?:[ \t]*-[ \t]*\S+\n)+)", text, re.M)
        first = re.search(r"-\s*(\S+)", block.group(1)).group(1) if block else ""
    family = first.split("/")[0] if first else ""
    return ROLE_FAMILY.get(family, "all")


def skill_lines() -> list[str]:
    lines = []
    for d in sorted(p for p in (ROOT / "skills").iterdir() if p.is_dir()):
        if not (d / "SKILL.md").is_file():
            continue
        lines.append(f"skill {d.name} {skill_role(d)}")
    return lines


def mirrored_link_lines(subdir: str) -> list[str]:
    return [f"link {p} .claude/{p}" for p in tracked_files(subdir)]


def main() -> int:
    lines = [HEADER.rstrip("\n")]
    lines += skill_lines()
    for subdir in ("agents", "hooks", "tools"):
        lines += mirrored_link_lines(subdir)
    lines += [
        "link settings.json .claude/settings.json",
        "link AGENTS.shared.md AGENTS.shared.md",
        "link AGENTS.files.md AGENTS.files.md",
        "template templates/AGENTS.md AGENTS.md",
        "prefix templates/CLAUDE.md CLAUDE.md",
    ]
    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
